
CREATE DATABASE IF NOT EXISTS np03cy4s250027;
USE np03cy4s250027;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS properties (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(150) NOT NULL,
  description TEXT,
  location VARCHAR(150) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  type VARCHAR(50),
  image VARCHAR(255),
  user_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_properties_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE CASCADE
);
